[phases.setup]
nixPkgs = ["dart"]

[phases.build]
cmds = [
  "dart pub global activate dart_frog_cli",
  "dart pub global run dart_frog_cli:dart_frog build",
  "dart compile exe build/bin/server.dart -o build/bin/server"
]

[start]
cmd = "./build/bin/server"
