name: probabilidade_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.3
  equatable: ^2.0.7
  intl: ^0.18.1
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
